import streamlit as st
import requests
import json
import base64
import io
from PIL import Image

# --- ページ設定 ---
st.set_page_config(page_title="Room AI Studio Pro", layout="wide")
st.title("🛋️ Room AI Studio (Pro)")
st.caption("Gemini 2.0 Flash (Vision) × Imagen 4.0 (Generation)")

# --- APIキー確認 ---
try:
    api_key = st.secrets["GEMINI_API_KEY"]
except:
    st.error("SecretsにAPIキーが設定されていません")
    st.stop()

# --- 画像処理関数 ---
def image_to_base64(uploaded_file):
    # 画像を少し小さくして通信エラーを防ぐ
    img = Image.open(uploaded_file)
    img.thumbnail((800, 800))
    # JPEG変換
    buffered = io.BytesIO()
    img.save(buffered, format="JPEG", quality=80)
    # Base64エンコード
    return base64.b64encode(buffered.getvalue()).decode('utf-8')

# --- メイン画面 ---
col1, col2 = st.columns([1, 1.2])

with col1:
    st.subheader("1. 家具を撮影")
    uploaded_file = st.file_uploader("家具の写真", type=["jpg", "png", "jpeg"])
    if uploaded_file:
        st.image(uploaded_file, width=300, caption="解析対象")

with col2:
    st.subheader("2. コーディネート設定")
    room = st.selectbox("部屋", ["リビング", "ダイニング", "寝室", "オフィス", "カフェ"])
    style = st.selectbox("スタイル", ["北欧モダン", "ヴィンテージ", "インダストリアル", "和モダン", "ラグジュアリー"])
    
    st.divider()
    generate_btn = st.button("✨ 生成スタート", type="primary")

# --- 実行ロジック ---
if generate_btn:
    if not uploaded_file:
        st.warning("写真をアップロードしてください")
    else:
        status = st.empty()
        status.info("🚀 Gemini 2.0 が家具を見ています...")
        
        try:
            # 1. Gemini 2.0 Flash で家具を分析 (REST API)
            base64_img = image_to_base64(uploaded_file)
            
            gemini_url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key={api_key}"
            
            gemini_payload = {
                "contents": [{
                    "parts": [
                        {"text": f"Describe this furniture in detail. Then write a high-quality English prompt for an image generator to place this furniture in a {style} {room}. The room should have cinematic lighting. Output ONLY the prompt text."},
                        {"inline_data": {"mime_type": "image/jpeg", "data": base64_img}}
                    ]
                }]
            }
            
            response_gemini = requests.post(gemini_url, headers={'Content-Type': 'application/json'}, data=json.dumps(gemini_payload))
            
            if response_gemini.status_code != 200:
                st.error(f"Gemini Error: {response_gemini.text}")
                st.stop()
                
            # プロンプト抽出
            prompt_text = response_gemini.json()['candidates'][0]['content']['parts'][0]['text']
            clean_prompt = prompt_text.replace('\n', ' ').strip()
            
            status.info("🎨 Imagen 4.0 が描画中... (Googleの最新AIを使用)")
            
            # 2. Imagen 4.0 で画像を生成 (REST API)
            # ※ここで最新モデル 'imagen-4.0-generate-001' を呼び出します
            imagen_url = f"https://generativelanguage.googleapis.com/v1beta/models/imagen-4.0-generate-001:predict?key={api_key}"
            
            imagen_payload = {
                "instances": [
                    {"prompt": clean_prompt}
                ],
                "parameters": {
                    "sampleCount": 1,
                    "aspectRatio": "4:3"
                }
            }
            
            response_imagen = requests.post(imagen_url, headers={'Content-Type': 'application/json'}, data=json.dumps(imagen_payload))
            
            if response_imagen.status_code == 200:
                result = response_imagen.json()
                
                # 画像データの取り出し (Base64で返ってきます)
                if 'predictions' in result:
                    b64_data = result['predictions'][0]['bytesBase64Encoded']
                    image_data = base64.b64decode(b64_data)
                    final_image = Image.open(io.BytesIO(image_data))
                    
                    status.success("生成完了！")
                    st.image(final_image, use_container_width=True, caption=f"Generated by Imagen 4.0 ({style})")
                    
                    with st.expander("使用したプロンプト"):
                        st.write(clean_prompt)
                else:
                    st.error("画像データが含まれていませんでした。")
                    st.write(result)
            else:
                st.error(f"Imagen Error: {response_imagen.status_code}")
                st.write(response_imagen.text)
                st.info("※ もし404エラーが出る場合、モデル名を 'imagen-3.0-generate-001' に変更してみてください。")

        except Exception as e:
            st.error(f"システムエラー: {e}")
